config/routes.rb
Rails.application.routes.draw do
  resources :listings
  resources :comments

  devise_for :users

  root to: "listings#index"
  # root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :commentable, polymorphic: true

end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
    @comment = Comment.new(comment_params)
    @listing = Listing.find(params[:comment][:commentable_id])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.commentable, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { redirect_to @listing, notice: 'Comment was notice created.' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

	private

    def comment_params
      params.require(:comment).permit(:user_id, :commentable_type, :commentable_id, :body)
    end

end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
	layout 'application'

	def index
		 @listings = Listing.all
	end
	
end 

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @comment = Comment.new
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    unless @listing.user == current_user
      redirect_to listings_path, notice: 'You are not authorized to edit this item.'
    end 
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    # @listing.user_id = params[:listing][:user_id]
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :price, :bitcoin_address, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/_header.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<!-- Navigation -->
<div class="fixed-top">
  <header class="topbar">
      <div class="container">
        <div class="row">
          <!-- social icon-->
          <!-- <div class="col-sm-12">
            <ul class="social-network">
              <li><a class="waves-effect waves-dark" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="waves-effect waves-dark" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="waves-effect waves-dark" href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a class="waves-effect waves-dark" href="#"><i class="fa fa-pinterest"></i></a></li>
              <li><a class="waves-effect waves-dark" href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div> -->

        </div>
      </div>
  </header>
  <nav class="navbar navbar-expand-lg navbar-dark mx-background-top-linear">
    <div class="container">
      <a class="navbar-brand" href="/" style="text-transform: uppercase;"> Riveroad</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">

        <ul class="navbar-nav ml-auto">

          <li class="nav-item <%= request.path == "/" ? 'active' : '' %>">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>

          <li class="nav-item <%= request.path != "/" && params[:controller] == "listings" ? 'active' : '' %>">
            <a class="nav-link" href="/listings">Listings</a>
          </li>

         
          <% if user_signed_in? %>
          <%#  if current_user.role == "admin" || current_user.role == "finance" || current_user.role == "ras" || current_user.role == "ra" %>
            <li class="nav-item">
              <a class="nav-link" href="#"><span class="fa fa-user"></span> <%= current_user.email %></a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_out"><span class="fa fa-sign-out"></span>Log out</a>
            </li>
          <%# end %>
          <% else %>
          
            <li class="nav-item <%= request.path == "/users/sign_in" ? 'active' : '' %>">
              <a class="nav-link" href="/users/sign_in"><span class="fa fa-user"></span>Login</a>
            </li>

            <li class="nav-item <%= request.path == "/users/sign_up" ? 'active' : '' %>">
              <a class="nav-link" href="/users/sign_up"><span class="fa fa-sign-in"></span>Sign Up</a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

<!-- -----------  Header Styling ----------- -->

<style type="text/css">
    body {
        margin: 0;
        font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        /*color: #212529;*/
        background-color: #f7f7f7;
    }
    .navbar {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        -ms-flex-align: center;
        align-items: center;
        -ms-flex-pack: justify;
        justify-content: space-between;
        padding: 5px;
    }

    /*
    headeer top
    */
    .topbar{
      background-color: #212529;
      padding: 0;
    }

    .topbar .container .row {
      margin:-7px;
      padding:0;
    }

    .topbar .container .row .col-md-12 { 
      padding:0;
    }

    .topbar p{
      margin:0;
      display:inline-block;
      font-size: 13px;
      color: #f1f6ff;
    }

    .topbar p > i{
      margin-right:5px;
    }
    .topbar p:last-child{
      text-align:right;
    } 

    header .navbar {
        margin-bottom: 0;
    }

    .topbar li.topbar {
        display: inline;
        padding-right: 18px;
        line-height: 52px;
        transition: all .3s linear;
    }

    .topbar li.topbar:hover {
        color: #1bbde8;
    }

    .topbar ul.info i {
        color: #131313;
        font-style: normal;
        margin-right: 8px;
        display: inline-block;
        position: relative;
        top: 4px;
    }

    .topbar ul.info li {
        float: right;
        padding-left: 30px;
        color: #ffffff;
        font-size: 13px;
        line-height: 44px;
    }

    .topbar ul.info i span {
        color: #aaa;
        font-size: 13px;
        font-weight: 400;
        line-height: 50px;
        padding-left: 18px;
    }

    ul.social-network {
      border:none;
      margin:0;
      padding:0;
    }

    ul.social-network li {
      border:none;  
      margin:0;
    }

    ul.social-network li i {
      margin:0;
    }

    ul.social-network li {
        display:inline;
        margin: 0 5px;
        border: 0px solid #2D2D2D;
        padding: 5px 0 0;
        width: 32px;
        display: inline-block;
        text-align: center;
        height: 32px;
        vertical-align: baseline;
        color: #000;
    }

    ul.social-network {
      list-style: none;
      margin: 5px 0 10px -25px;
      float: right;
    }

    .waves-effect {
        position: relative;
        cursor: pointer;
        display: inline-block;
        overflow: hidden;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        -webkit-tap-highlight-color: transparent;
        vertical-align: middle;
        z-index: 1;
        will-change: opacity, transform;
        transition: .3s ease-out;
        color: #fff;
    }
    a {
      color: #0a0a0a;
      text-decoration: none;
    }

    li {
        list-style-type: none;
    }
    .bg-image-full {
        background-position: center center;
        background-repeat: no-repeat;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        background-size: cover;
        -o-background-size: cover;
    }
    .bg-dark {
        background-color: #222!important;
    }

    .mx-background-top-linear {
        background: -webkit-linear-gradient(45deg, #54d400 48%, #1b1e21 48%);
        background: -webkit-linear-gradient(left, #54d400 48%, #1b1e21 48%);
        background: linear-gradient(45deg, #54d400 48%, #1b1e21 48%);
    }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Riveroad</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: 'layouts/header' %><br><br><br><br><br>
    </div>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<div class="container">
  <%= form_with(model: listing, local: true) do |form| %>
    <% if listing.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

        <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field col-lg-12">
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.label :name %>
      <%= form.text_field :name, autofocus: true, class: 'form-control'%>
    </div>

    <div class="field col-lg-12">
      <%= form.label :price %>
      <%= form.text_field :price,  class: 'form-control'%>
    </div>

    <div class="field col-lg-12">
      <%= form.label :bitcoin_address %>
      <%= form.text_field :bitcoin_address, class: 'form-control'%>
    </div>

    <div class="field col-lg-12">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>
   
    <div class="actions text-center">
      <%= form.submit class: 'new btn blue-gradient waves-effect waves-light' %>
    </div>
  <% end %>
</div>

<style type="text/css">
  .new{
    margin-top: 20px;
    margin-bottom: 20px;
  }
</style>

app/views/listings/edit.html.erb
<h1 class="text-center">Editing Listing</h1>

<%= render 'form', listing: @listing %>

<div class="text-center">
	<%= link_to 'Show', @listing, :class => 'btn blue-gradient waves-effect' %> |
	<%= link_to 'Back', listings_path,:class => 'btn peach-gradient waves-effect waves-light' %>
</div>

app/views/listings/index.html.erb
  <div class="container">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col-md-3">
      <h1 class="text-center">Listings</h1><br><br>
    </div>
    <div class="col-md-9 text-right">
      <%= link_to 'New Listing', new_listing_path ,:class => 'btn blue-gradient waves-effect waves-light'%>
    </div>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Bitcoin Address</th>
      </tr>
    </thead>

    <tbody>
      <% @listings.each do |listing| %>
        <tr>
          <td><%= listing.name %></td>
          <td><%= listing.price %></td>
          <td><%= link_to listing.bitcoin_address, listing.bitcoin_address, target: :blank if listing.bitcoin_address.present? %></td>
          <td>
            <%= link_to 'Show', listing, class: 'btn blue-gradient waves-effect waves-light' %>
            <% if current_user == listing.user %>
              <%= link_to 'Edit', edit_listing_path(listing),:class => 'btn peach-gradient waves-effect waves-light' %>
              <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-danger waves-effect waves-light' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/listings/new.html.erb
<h1 class="text-center">New Listing</h1><br><br>

<%= render 'form', listing: @listing %> 

<%= link_to 'Back', listings_path , :class => 'btn btn-success waves-effect waves-light'%>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<div class="container">
  <h1><%= @listing.name %></h1>
	<table class="table table-striped table-light">
    <thead>
      <tr>
        <th>Name</th>
        <th><%= @listing.name %></th>
      </tr>
      <tr>
        <th>Price</th>
        <th><%= @listing.price %></th>
      </tr>
      <tr>
        <th>Bitcoin Address</th>
        <th><%= link_to @listing.bitcoin_address, @listing.bitcoin_address, target: :blank if @listing.bitcoin_address.present? %></th>
      </tr>
      <tr>
        <th>Description</th>
        <th><%= @listing.description %></th>
      </tr>
    </thead>
  </table>

	
  <% if current_user == @listing.user  %>
  	<%= link_to 'Edit', edit_listing_path(@listing) , :class => 'btn btn-primary waves-effect waves-light'%>
  <% end%>

  <button type="reset" class="btn peach-gradient waves-effect waves-light" onclick="window.history.back();"><i class="fa fa-arrow-left"></i>Back</button>

  <br><br><br>
  <h1>Comments:</h1>

  <% if current_user %>
    <%= form_for @comment do |form| %>
      <div class="row">
        <div class="field col-lg-12">
          <%= form.hidden_field :user_id, value: current_user.id %>
          <%= form.hidden_field :commentable_type, value: "Listing" %>
          <%= form.hidden_field :commentable_id, value: @listing.id %>
          <%= form.text_area :body, autofocus: true, required: true, class: 'form-control'%>
        </div>
        <br><br><br>
        <div class="actions col-lg-1">
          <%= form.submit class: 'new btn blue-gradient waves-effect waves-light' %>
        </div>
      </div>
    <% end %>
  <% end %>

  <br><br>
  <div class="row">
    <% @listing.comments.each do |comment| %>
      <div class="col-lg-12">
        <p style="border-bottom: 1px solid;"><%= comment.user.email %>: <%= comment.body %></p>
      </div>
    <% end %>
  </div>

</div>	


<%#= link_to 'Back',"history.back()", :class => 'btn peach-gradient waves-effect waves-light' %>